### ISSUE TITLE
Always return "Value cannot be null. Parameter name: source"

### ISSUE THREAD

**Issue by hrntsm** [enmerk4r/GHPT#2]
First of all, thank your team for developing this wonderful component. I am very excited.

I'm trying it out, but it always gives me an "Value cannot be null. Parameter name: source" in an advise panel.
Is there something wrong with my input?

Token and model were set according to README.
The model is "gpt-3.5-turbo".

<img width="1262" alt="Screenshot 2023-06-26 at 9 51 24" src="https://github.com/enmerk4r/GHPT/assets/23289252/ec849a61-314e-40e3-bcce-59c2e82d5c02">

### environment

- win11
- ghpt v1.2(via package manager)

**Comment by clicketyclackety** [comment]
Hey @hrntsm can you try running this PR in debug and letting me know what the Advice panel says now?
#3

**Comment by hverbrugge** [comment]
I got the same error. You have to make sure when you type in the "GPT model*:" that it is the exact same name you have given the generated API key.

**Comment by hrntsm** [comment]
Hi @clicketyclackety,
I tried #3 and it works well.
<img width="1440" alt="Screenshot 2023-06-27 at 8 40 53" src="https://github.com/enmerk4r/GHPT/assets/23289252/9b59b7e2-f568-46e0-8614-6f2ba1794222">
But I couldn't get any meaningful results; I'm trying with GPT-3.5-turbo, so maybe it's a bit predictable and weak.
I have signed up for the GPT-4 waiting list and look forward to testing its capabilities in full.
Thank you for your quick response.

**Comment by clicketyclackety** [comment]
> Hi @clicketyclackety,
> I tried #3 and it works well.
> <img width="1440" alt="Screenshot 2023-06-27 at 8 40 53" src="https://github.com/enmerk4r/GHPT/assets/23289252/9b59b7e2-f568-46e0-8614-6f2ba1794222">
> But I couldn't get any meaningful results; I'm trying with GPT-3.5-turbo, so maybe it's a bit predictable and weak.
> I have signed up for the GPT-4 waiting list and look forward to testing its capabilities in full.
> Thank you for your quick response.
> 
> 

Awesome @hrntsm , I'll try it myself again and release a new build if it works for me too. Yeah it struggles with rectangles. I think it wants the component but currently it creates a parameter. I'll do some GPT3.5/4 comparisons

**Comment by lionmad** [comment]
Error: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
